# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH="/home/cgunn/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="spaceship";
SPACESHIP_CHAR_SYMBOL="$";
SPACESHIP_CHAR_SUFFIX=" ";
SPACESHIP_GIT_STATUS_DELETED="X";

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git autojump virtualenvwrapper)

source $ZSH/oh-my-zsh.sh

# User configuration

# Aliases
alias zconf="vim ~/.zshrc"
alias blu="bluetoothctl"
alias battery="cat /sys/class/power_supply/BAT0/capacity"

# Exporting
export PATH=/home/cgunn/.local/bin:$PATH
export NLTK_DATA=/home/cgunn/Data/nltk_data/
export GOPATH=/home/cgunn/Programs/gopath
export PATH=$GOPATH:$GOPATH/bin:$PATH
export PATH=$PATH:/home/cgunn/.gem/ruby/2.7.0/bin
export TEXMFHOME=$HOME/.texmf
export DEVKITPRO=/opt/devkitpro
export DEVKITARM=/opt/devkitpro/devkitARM
export DEVKITPPC=/opt/devkitpro/devkitPPC
export PATH=$PATH:${DEVKITARM}/bin

neofetch
