# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="spaceship"

plugins=(git colorize colored-man-pages vi-mode zsh-autosuggestions autojump)

source $ZSH/oh-my-zsh.sh

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#a89984'
SPACESHIP_DIR_TRUNC=5;
SPACESHIP_CHAR_SYMBOL="$";
SPACESHIP_CHAR_SUFFIX=" ";
SPACESHIP_GIT_STATUS_DELETED="X";
SPACESHIP_BATTERY_SHOW=false;
SPACESHIP_VI_MODE_SHOW=false;

# Path
path+=("/usr/local/bin" "/opt/HRT/bin" "/opt/homebrew/bin" "/opt/homebrew/sbin" "/opt/salt/bin" "/usr/local/sbin" "/opt/X11/bin")
export PATH

# Aliases
alias activate='source .venv/bin/activate'
# alias cat='bat -p --paging=never'
alias la='ls -lah'
alias ssh='kitty +kitten ssh'
alias h='kitty +kitten ssh shainternalgo62'
alias vim='nvim'

# Global Aliases


# Named Directory Hashes
